# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-08 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='address',
            managers=[
            ],
        ),
    ]
